### PR TITLE
Bugfix for PR 496 to add format_video_name function

### PR DESCRIPTION
**Pull request by BaoHuiling**
## Description

Extend rerank functionality to support handle unregular names with video name format function, for example names as follow
 [
        "op_1_0320241830_interval_0",
        "op_1_0320241830",
        "op_1_0320241830.mp4",
        "op_1_0320241830.avi"  # This will trigger the error
    ]

Fix file path for vdms retriever

## Issues

This a bug fix patch for #496 

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

N/A

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by XuhuiRen** [comment]
please add a test to check the error exception

**Comment by BaoHuiling** [comment]
> please add a test to check the error exception

In the corresponding test script?

**Review by XuhuiRen — APPROVED** [review]

**Comment by XuhuiRen** [comment]
> > please add a test to check the error exception
> 
> In the corresponding test script?

yes, it would be better to check the availability of the error exception for the wrong file name

**Comment by BaoHuiling** [comment]
> > > please add a test to check the error exception
> > 
> > 
> > In the corresponding test script?
> 
> yes, it would be better to check the availability of the error exception for the wrong file name

Test added with CI check passed🙂

**Comment by BaoHuiling** [comment]
@lvliang-intel @ftian1 Would you help to check and approve the PR? Thanks a lot

**Review by lvliang-intel — APPROVED** [review]

**Pull request merged**
