### PR TITLE
vLLM support for DocSum

### PR DESCRIPTION
**Pull request by sgurunat**
## Description

Added langchain vLLM support for  Summarization. Added new folder called vllm under summarization and have maintained the same file structure similar to tgi. Dockerfile, compose yaml and README contains details about how to build and use summarization with vLLM.

This also contains changes related to authentication support for remote vLLM endpoints in llm.py file.

Since model is mandatory parameter for vLLM updated the DocsumGateway to include the new parameter called "model" in Mega service gateway.py file

## Issues
N/A

## Type of change

- [x] New feature (non-breaking change which adds new functionality)

## Dependencies
N/A

### CODE REVIEW

**Comment by lvliang-intel** [comment]
@sgurunat,

Please update comps/llms/summarization/vllm/langchain/Dockerfile to .github/workflows/docker/compose/llms-compose-cd.yaml. The yaml is used for release images build.

**Comment by sgurunat** [comment]
@lvliang-intel - Updated the llm-compose-cd.yaml file. Its showing conflict

**Comment by lvliang-intel** [comment]
> @lvliang-intel - Updated the llm-compose-cd.yaml file. Its showing conflict

Please resolve the conflict. I can't help to resolve it.
image

**Comment by sgurunat** [comment]
@chensuyue @lvliang-intel Updated the git workflows to include vllm docsum build in llm-compose.yaml file

**Review by lvliang-intel — APPROVED** [review]

**Review by Spycsh — APPROVED** [review]

**Pull request merged**
