### PR TITLE
Optional container build instructions

### PR DESCRIPTION
**Pull request by tylertitsworth**
## Description

The summary of the proposed changes as long as the relevant motivation and context.

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [x] Others (enhancement, documentation, validation, etc.)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Review by jitendra42 — APPROVED** [review]
LGTM

**Review by ashahba — APPROVED** [review]
LGTM!

Thanks.

**Comment by chensuyue** [comment]
Let's merge the PR

**Comment by chensuyue** [comment]
There some conflict with main branch due to the user change PR, so I have merge this into the r0.8.1 first, and will submit another PR to main branch.

**Comment by chensuyue** [comment]
Sorry because of the conflict with main branch, I just merge it into r0.8.1 first, but just found this PR covered some main branch code that not target v0.8.1 release. So will revert the merge and add necessary part with a new PR.

**Pull request merged**
