### PR TITLE
Add initial Finetuning component

### PR DESCRIPTION
**Pull request by xwu99**
## Description

Add Finetuning microservice

Infra code: https://github.com/opea-project/GenAIInfra/pull/122
Example code: https://github.com/opea-project/GenAIExamples/pull/315

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by hshen14** [comment]
Please submit a RFC and suggest discussing with @ftian1. CC @lvliang-intel  @lkk12014402

**Comment by xwu99** [comment]
> Please submit a RFC and suggest discussing with @ftian1. CC @lvliang-intel @lkk12014402

@hshen14 Thanks. I will follow and draft a RFC.

**Comment by xwu99** [comment]
Drafting RFC #268

**Comment by kevinintel** [comment]
Fine tuning merged

**Pull request closed without merging**
