### PR TITLE
Quickfix: Replace fastapi dep with fastapi[standard]

### PR DESCRIPTION
**Pull request by sunnstix**
## Description

`fastapi` is now an alias for `fastapi-slim` as per the release of [version 1.112](https://github.com/fastapi/fastapi/releases/tag/0.112.0). 

> Before this, fastapi would include the standard dependencies, with Uvicorn and the fastapi-cli, etc.
And fastapi-slim would not include those standard dependencies.
Now fastapi doesn't include those standard dependencies unless you install with pip install "fastapi[standard]".

## Issues

#395 

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Dependencies

N/A

## Tests

N/A

### CODE REVIEW

**Comment by chensuyue** [comment]
Please fix the conflict.

**Review by lvliang-intel — APPROVED** [review]

**Comment by chensuyue** [comment]
@sunnstix please fix the conflict.

**Review by chensuyue — APPROVED** [review]

**Comment by chensuyue** [comment]
Please fix the conflict, so I can merge this PR. @sunnstix

**Comment by sunnstix** [comment]
@chensuyue I would argue that this change no longer needs to be implemented with the new inclusion of dependencies such as uvicorn independently. The standard fastapi package introduces dependencies outside of just uvicorn that are unnecessary and if we can manually install all the needed dependencies while using the lightweight version of fastapi, I think  that is better. Feel free to close this PR if you agree.

**Pull request closed without merging**
