### PR TITLE
Add no_proxy env for embedding-tei-server container

### PR DESCRIPTION
**Pull request by moting9**
## Description

Add no_proxy env for embedding-tei-server container

## Issues
In a proxy r&d or deployment environment ( need proxy to access external network, no proxy to access internal network)
we need to pass no_proxy setting to embedding-tei-server, otherwise by following https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/README.md

"TEI embedding service" access is OK, but inside "Embedding Microservice", it failed to access "Embedding Microservice".
some discussion in https://github.com/opea-project/GenAIExamples/issues/251

TEI Embedding Service
curl ${host_ip}:6006/embed \
    -X POST \
    -d '{"inputs":"What is Deep Learning?"}' \
    -H 'Content-Type: application/json'
Embedding Microservice
curl http://${host_ip}:6000/v1/embeddings\
  -X POST \
  -d '{"text":"hello"}' \
  -H 'Content-Type: application/json'

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

No dependency.  

## Tests

[Describe the tests that you ran to verify your changes.]
Follow (https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/README.md)  to  set up ChatQnA in a proxy  environment

TEI Embedding Service    ok
curl ${host_ip}:6006/embed \
    -X POST \
    -d '{"inputs":"What is Deep Learning?"}' \
    -H 'Content-Type: application/json'
Embedding Microservice    ko
curl http://${host_ip}:6000/v1/embeddings\
  -X POST \
  -d '{"text":"hello"}' \
  -H 'Content-Type: application/json'

### CODE REVIEW

**Comment by moting9** [comment]
After discussion with @huiyan2021   rerank container has the same issue, add no_proxy for both embedding and rerank

**Comment by lvliang-intel** [comment]
@moting9，

please also help to add no_proxy env for other microservices? thanks.

**Comment by moting9** [comment]
> @moting9，
> 
> please also help to add no_proxy env for other microservices? thanks.

Hello, @lvliang-intel,  changes in GenAIComps docker_compose.yaml   has no impact on GenAIExamples execution  because each GenAIExample has its own docker_compose.yaml,    no_proxy here is NOT necessary change for GenAIExample execution.     To keep alignment, I will try to add no_proxy along with http/https proxy setting in GenAIComps.

**Comment by moting9** [comment]
> @moting9，
> 
> please also help to add no_proxy env for other microservices? thanks.

@lvliang-intel    Done.  Please review. Thanks!

**Review by lvliang-intel — APPROVED** [review]

**Pull request merged**
