### PR TITLE
Prediction Guard embeddings component

### PR DESCRIPTION
**Pull request by sharanshirodkar7**
## Description

This PR introduces the embeddings component for Prediction Guard (PG). The component is designed to handle embedding generation and management, which is essential for various downstream tasks such as similarity search, clustering, and machine learning workflows.

## Issues

n/a

## Type of change

New feature (non-breaking change which adds new functionality)

## Dependencies

PREDICTIONGUARD_API_KEY needs to be added to CI/CD to test the microservice.

## Tests

The following tests were conducted to ensure proper functionality of the embeddings component:

	•	Unit tests for individual functions in the embeddings module.
	•	Integration tests to validate the complete embedding generation and storage workflow.
	•	Manual testing for Docker setup and microservice execution.

### CODE REVIEW

**Comment by sharanshirodkar7** [comment]
@chensuyue embeddings component ready for review.

**Comment by lvliang-intel** [comment]
@sharanshirodkar7,
please fix the pre-commit issue.

image

**Review by XuhuiRen — APPROVED** [review]

**Comment by sharanshirodkar7** [comment]
@lvliang-intel updated.

**Comment by sharanshirodkar7** [comment]
@chensuyue @lvliang-intel  all checks passed. Ready for review. Thanks

**Review by lvliang-intel — APPROVED** [review]

**Pull request merged**
