### PR TITLE
Fix the Retriever README error

### PR DESCRIPTION
**Pull request by zhlsunshine**
## Description

Fix the Retriever README error for TEI Service verification.
The model is embedding model in Retriever README and it's not a re-ranker model, the error showing as below:
```
{"error":"Backend error: model is not a re-ranker model","error_type":"Backend"}
```
So we need to verify embedding service.

## Issues

`n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

`n/a`.

## Tests

README file update.

### CODE REVIEW

**Review by XuhuiRen — APPROVED** [review]

**Comment by letonghan** [comment]
Hi @zhlsunshine , the reranker model is not needed here for `retriever` component.
If you got the error above, means that you need to start up another `TEI` service for `rerank` component, but not add it here.

**Comment by zhlsunshine** [comment]
Hi @letonghan,  okay, I just notice that there mentions the reranking model support in [comps/retrievers/pathway/langchain/README.md](https://github.com/opea-project/GenAIComps/tree/main/comps/retrievers/pathway/langchain#optionally-start-the-tei-embedder-service-separately), so I just make them the same. So should I remove it or just close this PR?

**Comment by letonghan** [comment]
> Hi @letonghan, okay, I just notice that there mentions the reranking model support in [comps/retrievers/pathway/langchain/README.md](https://github.com/opea-project/GenAIComps/tree/main/comps/retrievers/pathway/langchain#optionally-start-the-tei-embedder-service-separately), so I just make them the same. So should I remove it or just close this PR?

I think other modifications in this PR are right. 
You can keep this PR and remove the `model for reranking` part, the `curl 127.0.0.1:6060/rerank` part in `pgvector/readme`, `redis/readme` and `vdms/readme`.
Thanks : )

**Comment by zhlsunshine** [comment]
Hi @letonghan, thanks for your reviewing, PTAL for the new submitting!

**Review by letonghan — APPROVED** [review]
LGTM

**Pull request merged**
