### PR TITLE
fix pydantic version in agent component

### PR DESCRIPTION
**Pull request by minmin-intel**
## Description

change pydantic import in utils.py to fix the tool_renderer error.

## Issues
`n/a`.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Dependencies

No newly introduced 3rd party dependency.

## Tests

Unit test

### CODE REVIEW

**Review by xuechendi — APPROVED** [review]
LGTM

**Comment by xuechendi** [comment]
@lkk12014402 , please help to approve

**Comment by dcmiddle** [comment]
It looks like this version pinning went in less than a week ago.
Is reverting it just going to bring up the same conflict?
https://github.com/opea-project/GenAIComps/pull/782

**Comment by minmin-intel** [comment]
> It looks like this version pinning went in less than a week ago. Is reverting it just going to bring up the same conflict? #782

@dcmiddle Hi, the #782 PR was put in as a quick fix for [this PR](https://github.com/opea-project/GenAIExamples/pull/892) in GenAIExamples. Back then the unit tests for agent comp passed. But recently, we got a couple of reports from users that pydantic.v1 gave them errors, changing to import from pydantic fixed their errors. So we reached out to the author of PR892 and he was able to use pydantic instead of pydantic.v1 by changing his code. So we decided to change back to import from pydantic.

**Review by lvliang-intel — APPROVED** [review]

**Comment by dcmiddle** [comment]
Ok, thanks for the added background. Sounds like @JoshuaL3000 should be good with pydantic v2 then.

**Pull request merged**
