### PR TITLE
Bugfix for follow-up query with a .png image

### PR DESCRIPTION
**Pull request by mhbuehler**
## Description

Fixes a bug in the `dataprep-multimodal-redis` microservice where non-zero time metadata was being stored for .png images. This was resulting in an exception `ValueError: invalid literal for int()` being thrown and displayed in the MultimodalQnA UI during follow-up queries.

## Issues

Related to the [Image_and_Audio_Support_in_MultimodalQnA RFC](https://github.com/opea-project/docs/blob/main/community/rfcs/24-10-02-GenAIExamples-001-Image_and_Audio_Support_in_MultimodalQnA.md)

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Dependencies

N/A

## Tests

N/A

### CODE REVIEW

**Review by dmsuehir — APPROVED** [review]
LGTM, I tried it out with the GenAIExamples MultimodalQnA megaservice UI and it fixed the error that I was seeing earlier. Thanks!

**Review by ashahba — APPROVED** [review]
LGTM!

**Review by aice-support — APPROVED** [review]
the title mentions png, but understand that it is for mp4 video file. good to put some explanations for only mp4 files supported.

**Review by louie-tsai — APPROVED** [review]

**Comment by mhbuehler** [comment]
> the title mentions png, but understand that it is for mp4 video file. good to put some explanations for only mp4 files supported.

I added comments inline. The `mid_time_ms` variable was a very large negative number for `.png` files causing a crash in the UI. This fix is setting the time to 0 for all images, but leaving `.mp4` videos with the original calculated time.

**Pull request merged**
