### PR TITLE
fix: changed stream parameter to streaming in curl command

### PR DESCRIPTION
**Pull request by jjmaturino**
## Description

Incorrect json key set for curl command.

## Issues

N/A

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Dependencies
N/A

## Tests

Integration tests under tests/llms

### CODE REVIEW

**Comment by xiguiw** [comment]
@jjmaturino  

https://github.com/huggingface/text-generation-inference/blob/main/README.md#get-started
it's `stream`, not `streaming`.

Would you please let us in which format or protocol, `streaming` is used?

**Comment by jjmaturino** [comment]
@xiguiw .

On the Pydantic Model `LLMParamsDoc` , the attribute for **stream** is defined as **streaming**.

From my understanding and testing, Pydantic Model JSON Marshaling and Unmarshalling is based on the attribute variable name as the key in the json objects.

https://github.com/opea-project/GenAIComps/blob/8d6b4b0ac7a9a4f5858d8c08b157e01bacfe6388/comps/cores/proto/docarray.py#L187


This is why I changed stream to streaming to make the curl command work.

So if this is the desired case, we will need to change the pydantic model's key... that seems like a breaking change imo.

**Comment by jjmaturino** [comment]
@xiguiw Let me know if you want me to open up an issue and related pr for the topic discussed above!

**Comment by jjmaturino** [comment]
[Created issue ticket](https://github.com/opea-project/GenAIComps/issues/1078)

**Comment by xiguiw** [comment]
> @xiguiw .
> 
> On the Pydantic Model `LLMParamsDoc` , the attribute for **stream** is defined as **streaming**.
> 
> From my understanding and testing, Pydantic Model JSON Marshaling and Unmarshalling is based on the attribute variable name as the key in the json objects.
> 
> https://github.com/opea-project/GenAIComps/blob/8d6b4b0ac7a9a4f5858d8c08b157e01bacfe6388/comps/cores/proto/docarray.py#L187
> 
> This is why I changed stream to streaming to make the curl command work.
> 
> So if this is the desired case, we will need to change the pydantic model's key... that seems like a breaking change imo.

@jjmaturino 
Good catching!

Thanks！ Let me check it.

**Comment by xiguiw** [comment]
> @xiguiw No problem! Let me know if I can help.
> 
> Also, any tips on getting PR's reviewed more quickly in the future?
> 
> I want to contribute as much as I can to this project and would like a tight feedback loop 🚀
> 
> Hope you have a great week and happy new year!

@jjmaturino 
Thank you for your contribution!
Sorry for the late response for the PR review.
We noted this. Now we are trying to improve this process.

My suggestion for the PR's review feedback is to describe what the problems, feature that the PR for clearly, so we get to know the priority of the PR.

Happy new year!

**Comment by xiguiw** [comment]
Could this PR be closed?

**Comment by jjmaturino** [comment]
@xiguiw yes! I was talking about other prs

**Comment by jjmaturino** [comment]
Closed!

**Pull request closed without merging**
