### PR TITLE
Pinecone support for dataprep and retrieval microservice

### PR DESCRIPTION
**Pull request by pallavijaini0525**
## Description

Added the pinecone vector database-related config and docker files in data prep and retrieval microservice.

## Issues
n/a

## Type of change

New Feature

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

pinecone-client
langchain-pinecone

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Review by lvliang-intel — APPROVED** [review]

**Comment by chensuyue** [comment]
Require test scripts `test_vectorstores_langchain_pinecone.sh`, `test_retrievers_langchain_pinecone.sh`, `test_dataprep_pinecone.sh`

**Comment by chensuyue** [comment]
> Require test scripts `test_vectorstores_langchain_pinecone.sh`, `test_retrievers_langchain_pinecone.sh`, `test_dataprep_pinecone.sh`, like this one https://github.com/opea-project/GenAIComps/blob/main/tests/test_retrievers_langchain_pgvector.sh

@pallavijaini0525  please add the e2e test scripts.

**Comment by pallavijaini0525** [comment]
@chensuyue  -> Since Pinecone functions as a managed service and operates through APIs, I'm utilizing the Pinecone token to access its hosted vector database. Given that these tests are authentic functional tests, I'll need to pass my Pinecone token by configuring an environment variable and then integrating it into the following tests:

test_vectorstores_langchain_pinecone.sh
test_retrievers_langchain_pinecone.sh
test_dataprep_pinecone.sh
 
 any suggestions for this usecase?

**Comment by chensuyue** [comment]
I can pass a secrets for the test, like this one, it want be shown in the test scripts. You can send me by teams. 
image

And we can merge this PR first and add the test in another PR.

**Review by chensuyue — APPROVED** [review]

**Pull request merged**
