### PR TITLE
adding VDMS retriever and test - The VDMS retriever and test are implemented in this PR. PLEASE NOTE: The input for retriever is EmbedDoc and return is SearchedDoc (these types may need to be updated for service integration)  

### PR DESCRIPTION
**Pull request by s-gobriel**
## Description

The summary of the proposed changes as long as the relevant motivation and context.

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Review by avinashkarani — CHANGES_REQUESTED** [review]
Hi @arijit-intel, please update Dataperp component to support data ingestion to VDMS https://github.com/opea-project/GenAIComps/tree/main/comps/dataprep. This will help use case to easily take advantage of VDMS.

**Comment by s-gobriel** [comment]
@chensuyue can you please tag this PR with 'V0.9' Milestone

**Comment by s-gobriel** [comment]
submitted a new PR for the feature

**Comment by BaoHuiling** [comment]
> submitted a new PR for the feature

https://github.com/opea-project/GenAIComps/pull/539

**Pull request closed without merging**
