### PR TITLE
Add GPT-SoVITS microservice

### PR DESCRIPTION
**Pull request by Spycsh**
## Description

[GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS) allows you to to do zero-shot voice cloning and text to speech of multi languages such as English, Japanese, Korean, Cantonese and Chinese.

We will use this mainly for Chinese TTS part. We will integrate this into AudioQnA using no_wrapper and optimize this component later.

## Issues

na

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

None
## Tests

None

### CODE REVIEW

**Review by lvliang-intel — APPROVED** [review]

**Comment by lvliang-intel** [comment]
@Spycsh，
please fix ci issue.

image

**Comment by Spycsh** [comment]
Hi @chensuyue , could you please help look at this?

**Comment by Spycsh** [comment]
> Hi @chensuyue , could you please help look at this? seems there are some issues with the CI workflow.

Should fix now.

**Review by letonghan — APPROVED** [review]

**Comment by letonghan** [comment]
Do we need a ci test script for it?

**Pull request merged**
