### PR TITLE
Feature/elasticsearch vector store integration - Infosys

### PR DESCRIPTION
**Pull request by kkrishTa**
Infosys contribution to OPEA.
Elasticsearch vector store, dataprep and retriever

## Description

Elasticsearch vector store integration with dataprep and retriever with components

## Issues

NA

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

Langchain-elasticsearch

## Tests 

[tests/dataprep/test_dataprep_elasticsearch_langchain.sh](https://github.com/kkrishTa/GenAIComps/blob/feature/elasticsearch/tests/dataprep/test_dataprep_elasticsearch_langchain.sh)
[tests/retrievers/test_retrievers_elasticsearch_langchain.sh](https://github.com/kkrishTa/GenAIComps/blob/feature/elasticsearch/tests/retrievers/test_retrievers_elasticsearch_langchain.sh)

### CODE REVIEW

**Comment by lvliang-intel** [comment]
@kkrishTa,
Thanks for your contribution.
Please add 'comps/dataprep/elasticsearch/langchain/Dockerfile' to '.github/workflows/docker/compose/dataprep-compose.yaml' and add 'comps/retrievers/elasticsearch/langchain/Dockerfile' to '.github/workflows/docker/compose/retrievers-compose.yaml'. These yamls are used for release images build. Then the CI issue will be fixed.

**Comment by kkrishTa** [comment]
Hello @lvliang-intel 
Required changes are done to .github files. Can you please review/approve.

**Comment by ZePan110** [comment]
pre-commit.ci run

**Comment by ZePan110** [comment]
pre-commit.ci run

**Review by lvliang-intel — APPROVED** [review]

**Review by letonghan — APPROVED** [review]
lgtm

**Pull request merged**
