### PR TITLE
Helmchart

### PR DESCRIPTION
**Pull request by yongfengdu**
## Description

The summary of the proposed changes as long as the relevant motivation and context.

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by lianhao** [comment]
@yongfengdu  could you please split this into multiple independent PRs. It's too much files to review and make my browser hangs

**Comment by lianhao** [comment]
Also, gpt-sovits is one of the opea tts services, it shouldn't belong to 3rd party

**Comment by mkbhanda** [comment]
Indeed smaller commits more sane! Thank you for all the hard work @yongfengdu . BTW I noticed that mongodb had a redis description but I did not get very far in my review

**Comment by yongfengdu** [comment]
> Indeed smaller commits more sane! Thank you for all the hard work @yongfengdu . BTW I noticed that mongodb had a redis description but I did not get very far in my review

Good catch, the mongodb one(Chart.yaml) was copied from redis but leaked the replacement.
Yes, to use helm charts from original is a good idea, like the case of milvus. But for the 3rd party components like DB or VectorDB, it's more likely customer(Or in Example) will have their own optimized solution for production.

**Pull request closed without merging**
