### PR TITLE
Add SQL agent strategy

### PR DESCRIPTION
**Pull request by minmin-intel**
## Description

Add sql_agent_llama strategy

## Issues
https://github.com/opea-project/GenAIComps/issues/976

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds new functionality)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by minmin-intel** [comment]
UT tests `sql_agent_llama` on Gaudi.
I tested in my local system using openai model for `sql_agent` and passed. See screenshot below.
image

**Review by xuechendi — APPROVED** [review]
LGTM

**Review by lkk12014402 — APPROVED** [review]
LGTM

**Comment by ftian1** [comment]
this PR is not correct. it introduces a symblic link in root dir and add a data_hub. it's not allowed. pls revert it @minmin-intel

**Pull request merged**
