### PR TITLE
Add video-llama LVM microservice under lvms 

### PR DESCRIPTION
**Pull request by BaoHuiling**
## Description

Add support for video-llama LVM, which allows us to chat based on video file with LVM. The first usecase is VideoRAGQnA use case from Multimodal RAG proposal. 

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`. 
The RFC is still under review. https://github.com/opea-project/docs/pull/49

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

python:3.9-slim git git-lfs faiss-cpu sentencepiece pandas Pillow prometheus_fastapi_instrumentator ftfy decord einops iopath omegaconf opencv-python-headless timm torch torchaudio langchain-core transformers webdataset pytorchvideo DAMO-NLP-SG/Video-LLaMA(github repo) DAMO-NLP-SG/Video-LLaMA-2-7B-Finetuned (huggingface repo)

## Tests

Describe the tests that you ran to verify your changes.
https://github.com/siddhivelankar23/GenAIComps/blob/huiling-lvm/tests/test_lvms_video-llama.sh: build, start, validate, clean the microservice

### CODE REVIEW

**Comment by BaoHuiling** [comment]
@chensuyue  Hello Suyue, one question here, does the server that runs the CI test have access to the huggingface repo? I need to download files under  https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-7B-Finetuned/tree/main, but it seems that this step is bypassed or failed.

**Comment by chensuyue** [comment]
> @chensuyue Hello Suyue, one question here, does the server that runs the CI test have access to the huggingface repo? I need to download files under https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-2-7B-Finetuned/tree/main, but it seems that this step is bypassed or failed.

Yes, generally it should have. Use `$HF_TOKEN` in your test scripts.

**Comment by BaoHuiling** [comment]
@chensuyue Thank you for your comment, the image is download successfully. 

However another problem occured, the port that i'm using **9000** is already allocated. The old containers are already cleaned before running the test, could you help to check environment and remove the conflict?
image

**Comment by chensuyue** [comment]
> @chensuyue Thank you for your comment, the image is download successfully.
> 
> However another problem occured, the port that i'm using **9000** is already allocated. The old containers are already cleaned before running the test, could you help to check environment and remove the conflict? image

port 9000 is widely used, also in GenAIExamples CI test, and they share the test machine. So please change the port into `5xxx` which is suggested to be used in GenAIComps CI.

**Comment by BaoHuiling** [comment]
@Spycsh @lvliang-intel Please help to review the code, thanks!

**Comment by BaoHuiling** [comment]
Hello, @chensuyue  @Spycsh @lvliang-intel could anyone help to review the code? The DDL is tomorrow and we may need some time to fix required changes.🙂

**Review by Spycsh — APPROVED** [review]

**Comment by Spycsh** [comment]
Hi @BaoHuiling , thanks for this exciting feature! It looks good to me. I just have a few questions: This only support Xeon CPU/CUDA, right? Have you tried video-llama LVM on Gaudi? Do you have a plan on optimizing it on Gaudi? Don't worry, we will still merge it for now if the HPU support is not clear for this component.

**Comment by BaoHuiling** [comment]
> Hi @BaoHuiling , thanks for this exciting feature! It looks good to me. I just have a few questions: This only support Xeon CPU/CUDA, right? Have you tried video-llama LVM on Gaudi? Do you have a plan on optimizing it on Gaudi? Don't worry, we will still merge it for now if the HPU support is not clear for this component.

Thanks for the comment. Yes only Xeon is supported now. We haven't planned optimization on Gaudi yet, but I think it's good to have in the future.

**Review by lvliang-intel — APPROVED** [review]

**Pull request merged**
